version: "3.4"

x-rnode: &default-rnode
  image: coop.rchain/rnode:latest
  user: root
  networks:
    - rchain-net

x-wait-rnode: &wait-rnode
  build: .
  user: root
  networks:
    - rchain-net

services:
  boot:
    <<: *default-rnode
    container_name: rnode.boot
    ports:
      - "40403:40403"
      - "40401:40401"
      - "40402:40402"
    command:
      [
        "run",
        "-s",
        "--validator-private-key=$BOOTSTRAP_PRIVATE_KEY",
        "--host=$BOOTSTRAP_HOST",
        "--allow-private-addresses",
        "-n",
        "--synchrony-constraint-threshold=$SYNCHRONY_CONSTRAINT_THREDHOLD",
        "--wallets-file=/var/lib/rnode/wallets.txt",
        "--bonds-file=/var/lib/rnode/bonds.txt",
        "--deploy-timestamp=1",
        "--required-sigs=0",
        "--duration=1min",
        "--interval=10sec",
        "--fork-choice-stale-threshold=$FORK_CHOICE_STALE_THRESHOLD",
        "--fork-choice-check-if-stale-interval=$FORK_CHOICE_CHECK_IF_STALE_INTERVAL",
        "--reporting"
      ]
    volumes:
      - ./wallets.txt:/var/lib/rnode/wallets.txt
      - ./bonds.txt:/var/lib/rnode/bonds.txt
      - ./node.certificate.pem:/var/lib/rnode/node.certificate.pem
      - ./node.key.pem:/var/lib/rnode/node.key.pem

#  validator1:
#    <<: *wait-rnode
#    container_name: rnode.validator1
#    entrypoint: ["/bin/bash"]
#    command:
#      [
#        "/wait.sh",
#        "rnode.boot",
#        "40404",
#        "--",
#        "/opt/docker/bin/rnode",
#        "run",
#        "-b rnode://5b0390a7c34319310de2432cc2c9dc433043783e@$BOOTSTRAP_HOST?protocol=40400&discovery=40404",
#        "--validator-private-key=$VALIDATOR1_PRIVATE_KEY --host $VALIDATOR1_HOST",
#        "--allow-private-addresses -n --synchrony-constraint-threshold $SYNCHRONY_CONSTRAINT_THREDHOLD",
#        "--genesis-validator --deploy-timestamp $DEPLOY_TIMESTAMP --required-sigs 1",
#        "--wallets-file /var/lib/rnode/wallets.txt --bonds-file /var/lib/rnode/bonds.txt",
#        "--fork-choice-stale-threshold $FORK_CHOICE_STALE_THRESHOLD",
#        "--fork-choice-check-if-stale-interval $FORK_CHOICE_CHECK_IF_STALE_INTERVAL",
#      ]
#    volumes:
#      - ./wallets.txt:/var/lib/rnode/wallets.txt
#      - ./bonds.txt:/var/lib/rnode/bonds.txt
#      - ./wait.sh:/wait.sh

#  validator2:
#    <<: *wait-rnode
#    container_name: rnode.validator2
#    entrypoint: ["/bin/bash"]
#    command:
#      [
#        "/wait.sh",
#        "rnode.boot",
#        "40404",
#        "--",
#        "/opt/docker/bin/rnode",
#        "run",
#        "-b rnode://5b0390a7c34319310de2432cc2c9dc433043783e@$BOOTSTRAP_HOST?protocol=40400&discovery=40404",
#        "--validator-private-key=$VALIDATOR2_PRIVATE_KEY --host $VALIDATOR2_HOST",
#        "--allow-private-addresses -n --synchrony-constraint-threshold $SYNCHRONY_CONSTRAINT_THREDHOLD",
#        "--genesis-validator --deploy-timestamp $DEPLOY_TIMESTAMP --required-sigs 2",
#        "--wallets-file /var/lib/rnode/wallets.txt --bonds-file /var/lib/rnode/bonds.txt",
#        "--fork-choice-stale-threshold $FORK_CHOICE_STALE_THRESHOLD",
#        "--fork-choice-check-if-stale-interval $FORK_CHOICE_CHECK_IF_STALE_INTERVAL",
#      ]
#    volumes:
#      - ./wallets.txt:/var/lib/rnode/wallets.txt
#      - ./bonds.txt:/var/lib/rnode/bonds.txt
#      - ./wait.sh:/wait.sh

networks:
  rchain-net:
