version: "3.3"

services:
  propose:
    build: ./proposeImage
    command: ["--config", "/propose_config.yml"]
    volumes:
      - ./transfer.rho:/transfer.rho
      - ./propose_config.yml:/propose_config.yml
    networks:
      - rchain-net
networks:
  rchain-net:
